{% set name = "python-swiftclient" %}
{% set version = "4.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9e207b82ec31786f10db8fef6e205681c24997a0b600d28a194f9d15a90ed772

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - swift = swiftclient.shell:main
  noarch: python

requirements:
  host:
    - pbr
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - swiftclient

about:
  home: https://docs.openstack.org/python-swiftclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: OpenStack Object Storage API Client Library
  doc_url: https://docs.openstack.org/python-swiftclient/latest/
  dev_url: https://opendev.org/openstack/python-swiftclient

extra:
  recipe-maintainers:
    - tschoonj
