{% set name = "python-swiftclient" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f82298e4a48f7cbdd680f2638c85d1ca7ae1a76edbe30036d21b4cd7a29c09eb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - swift = swiftclient.shell:main
  noarch: python

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - requests
    - setuptools

test:
  imports:
    - swiftclient

about:
  home: https://docs.openstack.org/python-swiftclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: OpenStack Object Storage API Client Library
  doc_url: https://docs.openstack.org/python-swiftclient/latest/
  dev_url: https://opendev.org/openstack/python-swiftclient

extra:
  recipe-maintainers:
    - tschoonj
